// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VttTools.Data;

#nullable disable

namespace VttTools.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250415145318_SeedIdentity")]
    partial class SeedIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VttTools.Model.Game.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ActiveMap")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("VttTools.Model.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("019639ea-c7de-7e6f-b549-baf14386ad2f"),
                            ConcurrencyStamp = "b62e16a3-1d3a-4ae3-8c30-9bc628231f7a",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = new Guid("019639ea-c7de-786f-9f95-b397ca9509df"),
                            ConcurrencyStamp = "11d8a8d1-3a54-4464-890f-5e8c71b46c0b",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("VttTools.Model.Identity.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("VttTools.Model.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("019639ea-c7de-7a01-8548-41edfccde206"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "54c61fbd-4b9f-4a08-a6ce-c46443f8afb8",
                            DisplayName = "Master",
                            Email = "master@host.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Master",
                            NormalizedEmail = "MASTER@HOST.COM",
                            NormalizedUserName = "MASTER@HOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGCIPOjKQsg/WIuLEYnhnyHOsif13MaeUlO0J2ZVkMe41HuVFCqudWtLqGMKQXNBNA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "QAZB7SA3GUP4I2DQCDEDORPB5Q5ICUQG",
                            TwoFactorEnabled = false,
                            UserName = "master@host.com"
                        });
                });

            modelBuilder.Entity("VttTools.Model.Identity.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("VttTools.Model.Identity.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("VttTools.Model.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("019639ea-c7de-7a01-8548-41edfccde206"),
                            RoleId = new Guid("019639ea-c7de-7e6f-b549-baf14386ad2f")
                        });
                });

            modelBuilder.Entity("VttTools.Model.Identity.UserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("VttTools.Model.Game.Session", b =>
                {
                    b.OwnsMany("VttTools.Model.Game.SessionMap", "Maps", b1 =>
                        {
                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Number")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Number"));

                            b1.Property<string>("ImageUrl")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("MasterImageUrl")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("SessionId", "Number");

                            b1.ToTable("SessionMaps", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SessionId");

                            b1.OwnsMany("VttTools.Model.Game.SessionMapToken", "Tokens", b2 =>
                                {
                                    b2.Property<Guid>("SessionId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("MapNumber")
                                        .HasColumnType("int");

                                    b2.Property<int>("Number")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Number"));

                                    b2.Property<int?>("ControlledBy")
                                        .HasColumnType("int");

                                    b2.Property<string>("ImageUrl")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("nvarchar(256)");

                                    b2.Property<bool>("IsLocked")
                                        .HasMaxLength(256)
                                        .HasColumnType("bit");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b2.HasKey("SessionId", "MapNumber", "Number");

                                    b2.ToTable("SessionMapTokens", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SessionId", "MapNumber");

                                    b2.OwnsOne("VttTools.Model.Game.Position", "Position", b3 =>
                                        {
                                            b3.Property<Guid>("SessionMapTokenSessionId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<int>("SessionMapTokenMapNumber")
                                                .HasColumnType("int");

                                            b3.Property<int>("SessionMapTokenNumber")
                                                .HasColumnType("int");

                                            b3.Property<int>("Left")
                                                .HasColumnType("int");

                                            b3.Property<int>("Top")
                                                .HasColumnType("int");

                                            b3.HasKey("SessionMapTokenSessionId", "SessionMapTokenMapNumber", "SessionMapTokenNumber");

                                            b3.ToTable("SessionMapTokens");

                                            b3.WithOwner()
                                                .HasForeignKey("SessionMapTokenSessionId", "SessionMapTokenMapNumber", "SessionMapTokenNumber");
                                        });

                                    b2.OwnsOne("VttTools.Model.Game.Size", "Size", b3 =>
                                        {
                                            b3.Property<Guid>("SessionMapTokenSessionId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<int>("SessionMapTokenMapNumber")
                                                .HasColumnType("int");

                                            b3.Property<int>("SessionMapTokenNumber")
                                                .HasColumnType("int");

                                            b3.Property<int>("Height")
                                                .HasColumnType("int");

                                            b3.Property<int>("Width")
                                                .HasColumnType("int");

                                            b3.HasKey("SessionMapTokenSessionId", "SessionMapTokenMapNumber", "SessionMapTokenNumber");

                                            b3.ToTable("SessionMapTokens");

                                            b3.WithOwner()
                                                .HasForeignKey("SessionMapTokenSessionId", "SessionMapTokenMapNumber", "SessionMapTokenNumber");
                                        });

                                    b2.Navigation("Position")
                                        .IsRequired();

                                    b2.Navigation("Size")
                                        .IsRequired();
                                });

                            b1.OwnsOne("VttTools.Model.Game.Grid", "Grid", b2 =>
                                {
                                    b2.Property<Guid>("SessionMapSessionId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("SessionMapNumber")
                                        .HasColumnType("int");

                                    b2.HasKey("SessionMapSessionId", "SessionMapNumber");

                                    b2.ToTable("SessionMaps");

                                    b2.WithOwner()
                                        .HasForeignKey("SessionMapSessionId", "SessionMapNumber");

                                    b2.OwnsOne("VttTools.Model.Game.Cell", "Cell", b3 =>
                                        {
                                            b3.Property<Guid>("GridSessionMapSessionId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<int>("GridSessionMapNumber")
                                                .HasColumnType("int");

                                            b3.Property<double>("Height")
                                                .HasColumnType("float");

                                            b3.Property<double>("Width")
                                                .HasColumnType("float");

                                            b3.HasKey("GridSessionMapSessionId", "GridSessionMapNumber");

                                            b3.ToTable("SessionMaps");

                                            b3.WithOwner()
                                                .HasForeignKey("GridSessionMapSessionId", "GridSessionMapNumber");
                                        });

                                    b2.OwnsOne("VttTools.Model.Game.Offset", "Offset", b3 =>
                                        {
                                            b3.Property<Guid>("GridSessionMapSessionId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<int>("GridSessionMapNumber")
                                                .HasColumnType("int");

                                            b3.Property<double>("Left")
                                                .HasColumnType("float");

                                            b3.Property<double>("Top")
                                                .HasColumnType("float");

                                            b3.HasKey("GridSessionMapSessionId", "GridSessionMapNumber");

                                            b3.ToTable("SessionMaps");

                                            b3.WithOwner()
                                                .HasForeignKey("GridSessionMapSessionId", "GridSessionMapNumber");
                                        });

                                    b2.Navigation("Cell");

                                    b2.Navigation("Offset");
                                });

                            b1.OwnsOne("VttTools.Model.Game.Size", "Size", b2 =>
                                {
                                    b2.Property<Guid>("SessionMapSessionId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("SessionMapNumber")
                                        .HasColumnType("int");

                                    b2.Property<int>("Height")
                                        .HasColumnType("int");

                                    b2.Property<int>("Width")
                                        .HasColumnType("int");

                                    b2.HasKey("SessionMapSessionId", "SessionMapNumber");

                                    b2.ToTable("SessionMaps");

                                    b2.WithOwner()
                                        .HasForeignKey("SessionMapSessionId", "SessionMapNumber");
                                });

                            b1.Navigation("Grid")
                                .IsRequired();

                            b1.Navigation("Size")
                                .IsRequired();

                            b1.Navigation("Tokens");
                        });

                    b.OwnsMany("VttTools.Model.Game.SessionMessage", "Messages", b1 =>
                        {
                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("SentAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(4096)
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("SentBy")
                                .HasColumnType("int");

                            b1.Property<int?>("SentTo")
                                .HasColumnType("int");

                            b1.HasKey("SessionId", "SentAt");

                            b1.ToTable("SessionMassages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.OwnsMany("VttTools.Model.Game.SessionPlayer", "Players", b1 =>
                        {
                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.HasKey("SessionId", "UserId");

                            b1.ToTable("SessionPlayers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.Navigation("Maps");

                    b.Navigation("Messages");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("VttTools.Model.Identity.RoleClaim", b =>
                {
                    b.HasOne("VttTools.Model.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VttTools.Model.Identity.UserClaim", b =>
                {
                    b.HasOne("VttTools.Model.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VttTools.Model.Identity.UserLogin", b =>
                {
                    b.HasOne("VttTools.Model.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VttTools.Model.Identity.UserRole", b =>
                {
                    b.HasOne("VttTools.Model.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VttTools.Model.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VttTools.Model.Identity.UserToken", b =>
                {
                    b.HasOne("VttTools.Model.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
