global using System.Diagnostics.CodeAnalysis;
global using System.Linq;
global using System.Net;
global using System.Security.Claims;
global using System.Text.Encodings.Web;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using System.Threading.Tasks;

global using DotNetToolbox.Results;

global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Cors.Infrastructure;
global using Microsoft.AspNetCore.Diagnostics;
global using Microsoft.AspNetCore.Diagnostics.HealthChecks;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Diagnostics.HealthChecks;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;

global using VttTools.Data;
global using VttTools.Data.Extensions;
global using VttTools.Data.Options;
global using VttTools.Extensions;
global using VttTools.Game.EndpointMappers;
global using VttTools.Game.Endpoints;
global using VttTools.Game.Extensions;
global using VttTools.Game.Handlers;
global using VttTools.Game.Services;
global using VttTools.Game.Sessions.ApiContracts;
global using VttTools.Game.Sessions.Model;
global using VttTools.Game.Sessions.ServiceContracts;
global using VttTools.Game.Sessions.Services;
global using VttTools.Game.Sessions.Storage;
global using VttTools.Middlewares;
global using VttTools.Utilities;