###################################
# Asset Endpoints
###################################

### GET All Assets
GET {{baseUrl}}/api/assets/ HTTP/1.1
Accept: application/json
X-USER: {{x-user}}

### GET Asset by Id
GET {{baseUrl}}/api/assets/00000000-0000-0000-0000-000000000001 HTTP/1.1
Accept: application/json
X-USER: {{x-user}}

### POST Create Asset
POST {{baseUrl}}/api/assets/ HTTP/1.1
Content-Type: application/json
X-USER: {{x-user}}

{
    "name": "New Asset",
    "description": "Description for new asset"
}

### PATCH Update Asset
PATCH {{baseUrl}}/api/assets/00000000-0000-0000-0000-000000000001 HTTP/1.1
Content-Type: application/json
X-USER: {{x-user}}

{
    "name": "Updated Asset Name"
}

### DELETE Asset
DELETE {{baseUrl}}/api/assets/00000000-0000-0000-0000-000000000001 HTTP/1.1
X-USER: {{x-user}}

### POST Upload Asset File
POST {{baseUrl}}/api/assets/00000000-0000-0000-0000-000000000001/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=---011000010111000001101001
X-USER: {{x-user}}

---011000010111000001101001
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

Test file content
---011000010111000001101001--

###################################
# Episode Endpoints
###################################

### GET Episode by Id
GET {{baseUrl}}/api/episodes/00000000-0000-0000-0000-000000000002 HTTP/1.1
Accept: application/json
X-USER: {{x-user}}

### PATCH Update Episode
PATCH {{baseUrl}}/api/episodes/00000000-0000-0000-0000-000000000002 HTTP/1.1
Content-Type: application/json
X-USER: {{x-user}}

{
    "title": "Updated Episode Title"
}

### DELETE Episode
DELETE {{baseUrl}}/api/episodes/00000000-0000-0000-0000-000000000002 HTTP/1.1
X-USER: {{x-user}}

### POST Clone Episode
POST {{baseUrl}}/api/episodes/00000000-0000-0000-0000-000000000002/clone HTTP/1.1
Content-Type: application/json
X-USER: {{x-user}}

{}

### GET Episode Assets
GET {{baseUrl}}/api/episodes/00000000-0000-0000-0000-000000000002/assets HTTP/1.1
Accept: application/json
X-USER: {{x-user}}

### POST Add Asset to Episode
POST {{baseUrl}}/api/episodes/00000000-0000-0000-0000-000000000002/assets/00000000-0000-0000-0000-000000000003 HTTP/1.1
Content-Type: application/json
X-USER: {{x-user}}

{}

### DELETE Remove Asset from Episode
DELETE {{baseUrl}}/api/episodes/00000000-0000-0000-0000-000000000002/assets/00000000-0000-0000-0000-000000000003 HTTP/1.1
X-USER: {{x-user}}

###################################
# Meeting Endpoints
###################################

### GET All Meetings
GET {{baseUrl}}/api/meetings/ HTTP/1.1
Accept: application/json
X-USER: {{x-user}}

### GET Meeting by Id
GET {{baseUrl}}/api/meetings/00000000-0000-0000-0000-000000000004 HTTP/1.1
Accept: application/json
X-USER: {{x-user}}

### POST Create Meeting
POST {{baseUrl}}/api/meetings/ HTTP/1.1
Content-Type: application/json
X-USER: {{x-user}}

{
    "title": "New Meeting",
    "description": "Meeting description"
}

### PATCH Update Meeting
PATCH {{baseUrl}}/api/meetings/00000000-0000-0000-0000-000000000004 HTTP/1.1
Content-Type: application/json
X-USER: {{x-user}}

{
    "title": "Updated Meeting Title"
}

### DELETE Meeting
DELETE {{baseUrl}}/api/meetings/00000000-0000-0000-0000-000000000004 HTTP/1.1
X-USER: {{x-user}}

### POST Join Meeting
POST {{baseUrl}}/api/meetings/00000000-0000-0000-0000-000000000004/join HTTP/1.1
Content-Type: application/json
X-USER: {{x-user}}

{}

### POST Leave Meeting
POST {{baseUrl}}/api/meetings/00000000-0000-0000-0000-000000000004/leave HTTP/1.1
Content-Type: application/json
X-USER: {{x-user}}

{}

### POST Activate Episode in Meeting
POST {{baseUrl}}/api/meetings/00000000-0000-0000-0000-000000000004/episodes/00000000-0000-0000-0000-000000000002/activate HTTP/1.1
Content-Type: application/json
X-USER: {{x-user}}

{}

### POST Start Meeting
POST {{baseUrl}}/api/meetings/00000000-0000-0000-0000-000000000004/start HTTP/1.1
Content-Type: application/json
X-USER: {{x-user}}

{}

### POST Stop Meeting
POST {{baseUrl}}/api/meetings/00000000-0000-0000-0000-000000000004/stop HTTP/1.1
Content-Type: application/json
X-USER: {{x-user}}

{}

###################################
# Health Endpoints
###################################

### GET Health Check
GET {{baseUrl}}/health HTTP/1.1
Accept: application/json
X-USER: {{x-user}}

### GET Alive Check
GET {{baseUrl}}/alive HTTP/1.1
Accept: application/json
X-USER: {{x-user}}

###################################
# Adventure Endpoints
###################################

### GET All Adventures
GET {{baseUrl}}/api/adventures/ HTTP/1.1
Accept: application/json
X-USER: {{x-user}}

### GET Adventure by Id
GET {{baseUrl}}/api/adventures/00000000-0000-0000-0000-000000000005 HTTP/1.1
Accept: application/json
X-USER: {{x-user}}

### POST Create Adventure
POST {{baseUrl}}/api/adventures/ HTTP/1.1
Content-Type: application/json
X-USER: {{x-user}}

{
    "name": "New Adventure",
    "description": "Adventure description"
}

### PATCH Update Adventure
PATCH {{baseUrl}}/api/adventures/00000000-0000-0000-0000-000000000005 HTTP/1.1
Content-Type: application/json
X-USER: {{x-user}}

{
    "name": "Updated Adventure Name"
}

### DELETE Adventure
DELETE {{baseUrl}}/api/adventures/00000000-0000-0000-0000-000000000005 HTTP/1.1
X-USER: {{x-user}}

### POST Clone Adventure
POST {{baseUrl}}/api/adventures/00000000-0000-0000-0000-000000000005/clone HTTP/1.1
Content-Type: application/json
X-USER: {{x-user}}

{}

### GET Adventure Episodes
GET {{baseUrl}}/api/adventures/00000000-0000-0000-0000-000000000005/episodes HTTP/1.1
Accept: application/json
X-USER: {{x-user}}

### POST Add Episode to Adventure
POST {{baseUrl}}/api/adventures/00000000-0000-0000-0000-000000000005/episodes/00000000-0000-0000-0000-000000000002 HTTP/1.1
Content-Type: application/json
X-USER: {{x-user}}

{}

### DELETE Remove Episode from Adventure
DELETE {{baseUrl}}/api/adventures/00000000-0000-0000-0000-000000000005/episodes/00000000-0000-0000-0000-000000000002 HTTP/1.1
X-USER: {{x-user}}