namespace WebApi.EntityFrameworkCore.Utilities;

public static class PropertyBuilderExtensions {
    public static void SetDefaultValueGeneration(this PropertyBuilder modelBuilder) {
        var isAutoGenerated = (modelBuilder.Metadata.ValueGenerated & ValueGenerated.OnAdd) != 0;
        if (!isAutoGenerated)
            return;
        var propertyType = modelBuilder.Metadata.PropertyInfo!.PropertyType;
        switch (propertyType.FullName) {
            case { } s when s == typeof(Guid).FullName:
                modelBuilder.HasValueGenerator<Version7GuidValueGenerator>();
                break;
            case { } s when s == typeof(DateTimeOffset).FullName:
                modelBuilder.HasValueGenerator<DateTimeOffsetValueGenerator>();
                break;
            case { } s when s == typeof(DateTime).FullName:
                modelBuilder.HasValueGenerator<DateTimeValueGenerator>();
                break;
        }
    }
}
