@AuthService_HostAddress = https://localhost:7166
@AuthService_ClientCredentials = Q2xpZW50SWQ6Q2xpZW50U2VjcmV0

POST {{AuthService_HostAddress}}/token
Authorization: Basic {{AuthService_ClientCredentials}}
Content-Type: application/json

###
