global using System.ComponentModel.DataAnnotations;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.Net.Http;
global using System.Net.Http.Json;
global using System.Security.Claims;
global using System.Text;
global using System.Text.Encodings.Web;
global using System.Text.Json;
global using System.Text.Json.Serialization;

global using DotNetToolbox.Results;

global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Authorization;
global using Microsoft.AspNetCore.Components.Forms;
global using Microsoft.AspNetCore.Components.Routing;
global using Microsoft.AspNetCore.Components.Server;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Http.Extensions;
global using Microsoft.AspNetCore.Http.Features;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.UI.Services;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.SignalR.Client;
global using Microsoft.AspNetCore.WebUtilities;
global using Microsoft.Extensions.Diagnostics.HealthChecks;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Primitives;
global using Microsoft.IdentityModel.Tokens;

global using VttTools.Assets.ApiContracts;
global using VttTools.Assets.Model;
global using VttTools.Common.Model;
global using VttTools.Data;
global using VttTools.Extensions;
global using VttTools.Game.Sessions.ApiContracts;
global using VttTools.Identity.Model;
global using VttTools.Library.Adventures.ApiContracts;
global using VttTools.Library.Adventures.Model;
global using VttTools.Library.Scenes.Model;
global using VttTools.Utilities;
global using VttTools.WebApp.Components;
global using VttTools.WebApp.Contracts.Assets;
global using VttTools.WebApp.Contracts.Game;
global using VttTools.WebApp.Contracts.Game.Chat.Models;
global using VttTools.WebApp.Contracts.Game.Sessions;
global using VttTools.WebApp.Contracts.Library;
global using VttTools.WebApp.Contracts.Library.Adventure;
global using VttTools.WebApp.Contracts.Library.Scenes;
global using VttTools.WebApp.Extensions;
global using VttTools.WebApp.Server.Clients;
global using VttTools.WebApp.Server.Extensions;
global using VttTools.WebApp.Server.Pages.Account;
global using VttTools.WebApp.Server.Pages.Account.Manage;
global using VttTools.WebApp.Server.Utilities;
global using VttTools.WebApp.Utilities;

global using static DotNetToolbox.Ensure;

global using GameSession = VttTools.Game.Sessions.Model.GameSession;
global using InputError = DotNetToolbox.Error;