// <auto-generated />
#nullable disable

namespace VttTools.Data.MigrationService.Migrations;
/// <inheritdoc />
public partial class RefactorToNamedSize : Migration {
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder) {

    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder) {

    }
}
