// <auto-generated />
#nullable disable

namespace VttTools.Data.MigrationService.Migrations;

/// <inheritdoc />
public partial class AddAssetNavigationToEncouterEffect : Migration {
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder) {
        migrationBuilder.CreateIndex(
            name: "IX_EncounterEffects_AssetId",
            table: "EncounterEffects",
            column: "AssetId");

        migrationBuilder.AddForeignKey(
            name: "FK_EncounterEffects_Assets_AssetId",
            table: "EncounterEffects",
            column: "AssetId",
            principalTable: "Assets",
            principalColumn: "Id",
            onDelete: ReferentialAction.Cascade);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder) {
        migrationBuilder.DropForeignKey(
            name: "FK_EncounterEffects_Assets_AssetId",
            table: "EncounterEffects");

        migrationBuilder.DropIndex(
            name: "IX_EncounterEffects_AssetId",
            table: "EncounterEffects");
    }
}
