// <auto-generated />
#nullable disable

namespace VttTools.Data.MigrationService.Migrations;

/// <inheritdoc />
public partial class SeedIdentityData : Migration {
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder) {
        migrationBuilder.InsertData(
            table: "Roles",
            columns: ["Id", "ConcurrencyStamp", "Name", "NormalizedName"],
            values: new object[,]
            {
                { new Guid("019639ea-c7de-786f-9f95-b397ca9509df"), "11d8a8d1-3a54-4464-890f-5e8c71b46c0b", "User", "USER" },
                { new Guid("019639ea-c7de-7e6f-b549-baf14386ad2f"), "b62e16a3-1d3a-4ae3-8c30-9bc628231f7a", "Administrator", "ADMINISTRATOR" }
            });

        migrationBuilder.InsertData(
            table: "Users",
            columns: ["Id", "AccessFailedCount", "AvatarId", "ConcurrencyStamp", "DisplayName", "Email", "EmailConfirmed", "LockoutEnabled", "LockoutEnd", "Name", "NormalizedEmail", "NormalizedUserName", "PasswordHash", "PhoneNumber", "PhoneNumberConfirmed", "SecurityStamp", "TwoFactorEnabled", "UnitSystem", "UserName"],
            values: [new Guid("019639ea-c7de-7a01-8548-41edfccde206"), 0, null, "54c61fbd-4b9f-4a08-a6ce-c46443f8afb8", "Master", "master@host.com", true, false, null, "Master", "MASTER@HOST.COM", "MASTER@HOST.COM", "AQAAAAIAAYagAAAAEGCIPOjKQsg/WIuLEYnhnyHOsif13MaeUlO0J2ZVkMe41HuVFCqudWtLqGMKQXNBNA==", null, false, "QAZB7SA3GUP4I2DQCDEDORPB5Q5ICUQG", false, 0, "master@host.com"]);

        migrationBuilder.InsertData(
            table: "UserRoles",
            columns: ["RoleId", "UserId"],
            values: [new Guid("019639ea-c7de-7e6f-b549-baf14386ad2f"), new Guid("019639ea-c7de-7a01-8548-41edfccde206")]);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder) {
        migrationBuilder.DeleteData(
            table: "Roles",
            keyColumn: "Id",
            keyValue: new Guid("019639ea-c7de-786f-9f95-b397ca9509df"));

        migrationBuilder.DeleteData(
            table: "UserRoles",
            keyColumns: ["RoleId", "UserId"],
            keyValues: [new Guid("019639ea-c7de-7e6f-b549-baf14386ad2f"), new Guid("019639ea-c7de-7a01-8548-41edfccde206")]);

        migrationBuilder.DeleteData(
            table: "Roles",
            keyColumn: "Id",
            keyValue: new Guid("019639ea-c7de-7e6f-b549-baf14386ad2f"));

        migrationBuilder.DeleteData(
            table: "Users",
            keyColumn: "Id",
            keyValue: new Guid("019639ea-c7de-7a01-8548-41edfccde206"));
    }
}
