// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VttTools.Data;

#nullable disable

namespace VttTools.Data.MigrationService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251218172038_CreateApplicationSchema")]
    partial class CreateApplicationSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VttTools.Data.AI.Entities.AiModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContentType");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ContentType", "IsDefault");

                    b.ToTable("AiProviderModels", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.AI.Entities.PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("NegativePromptTemplate")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid?>("ReferenceImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPromptTemplate")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("1.0-draft");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.HasIndex("ReferenceImageId");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("PromptTemplates", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.AI.Entities.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("HealthEndpoint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AiProviderConfigs", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Assets.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PortraitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Subtype")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_Assets_OwnerId");

                    b.HasIndex("PortraitId");

                    b.HasIndex("IsPublic", "IsPublished")
                        .HasDatabaseName("IX_Assets_IsPublic_IsPublished");

                    b.HasIndex("Kind", "Category", "Type")
                        .HasDatabaseName("IX_Assets_Taxonomy");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Assets.Entities.AssetStatBlockValue", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssetId", "Level", "Key");

                    b.ToTable("AssetStatBlockValues", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Assets.Entities.AssetToken", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.HasKey("AssetId", "TokenId");

                    b.HasIndex("TokenId");

                    b.HasIndex("AssetId", "Index")
                        .IsUnique();

                    b.ToTable("AssetTokens", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Audit.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Payload")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("EntityType");

                    b.HasIndex("Timestamp")
                        .IsDescending();

                    b.HasIndex("UserId");

                    b.HasIndex("Timestamp", "UserId")
                        .IsDescending(true, false);

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Game.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("GameSessions", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Game.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Recurrence", "VttTools.Data.Game.Entities.Schedule.Recurrence#Recurrence", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Count")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(1);

                            b1.PrimitiveCollection<string>("Days")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("[]");

                            b1.Property<string>("Frequency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("Daily");

                            b1.Property<int>("Interval")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(1);

                            b1.Property<DateTimeOffset?>("Until")
                                .HasColumnType("datetimeoffset");

                            b1.Property<bool>("UseWeekdays")
                                .HasColumnType("bit");
                        });

                    b.HasKey("Id");

                    b.ToTable("Schedule", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Game.Entities.StatBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("StatBlocks", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Jobs.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EstimatedDuration")
                        .HasColumnType("time");

                    b.Property<Guid>("OwnerId")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Result")
                        .HasMaxLength(8192)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Jobs.Entities.JobItem", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasMaxLength(8192)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("JobId", "Index");

                    b.HasIndex("Status");

                    b.ToTable("JobItems", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.Adventure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BackgroundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOneShot")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("WorldId");

                    b.ToTable("Adventures", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BackgroundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundId");

                    b.HasIndex("WorldId");

                    b.ToTable("Campaigns", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.Encounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AmbientLight")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Default");

                    b.Property<Guid?>("AmbientSoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BackgroundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("GroundElevation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Weather")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Clear");

                    b.Property<float>("ZoomLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(1f);

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Grid", "VttTools.Data.Library.Entities.Encounter.Grid#Grid", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Scale")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("float")
                                .HasDefaultValue(5.0)
                                .HasColumnName("GridScale");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("NoGrid")
                                .HasColumnName("GridType");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "CellSize", "VttTools.Data.Library.Entities.Encounter.Grid#Grid.CellSize#CellSize", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<double>("Height")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("float")
                                        .HasDefaultValue(64.0)
                                        .HasColumnName("GridCellHeight");

                                    b2.Property<double>("Width")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("float")
                                        .HasDefaultValue(64.0)
                                        .HasColumnName("GridCellWidth");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Offset", "VttTools.Data.Library.Entities.Encounter.Grid#Grid.Offset#Offset", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<double>("Left")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("float")
                                        .HasDefaultValue(0.0)
                                        .HasColumnName("GridOffsetLeft");

                                    b2.Property<double>("Top")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("float")
                                        .HasDefaultValue(0.0)
                                        .HasColumnName("GridOffsetTop");
                                });
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Panning", "VttTools.Data.Library.Entities.Encounter.Panning#Point", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("X")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("float")
                                .HasDefaultValue(0.0)
                                .HasColumnName("PanningX");

                            b1.Property<double>("Y")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("float")
                                .HasDefaultValue(0.0)
                                .HasColumnName("PanningY");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AdventureId");

                    b.HasIndex("AmbientSoundId");

                    b.HasIndex("BackgroundId");

                    b.ToTable("Encounters", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.EncounterAsset", b =>
                {
                    b.Property<Guid>("EncounterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ControlledBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Elevation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rotation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Frame", "VttTools.Data.Library.Entities.EncounterAsset.Frame#Frame", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Background")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("")
                                .HasColumnName("FrameBackground");

                            b1.Property<string>("BorderColor")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("white")
                                .HasColumnName("FrameBorderColor");

                            b1.Property<int>("BorderThickness")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(1)
                                .HasColumnName("FrameBorderThickness");

                            b1.Property<string>("Shape")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(max)")
                                .HasDefaultValue("Square")
                                .HasColumnName("FrameShape");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Position", "VttTools.Data.Library.Entities.EncounterAsset.Position#Position", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("X")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("float")
                                .HasDefaultValue(0.0)
                                .HasColumnName("X");

                            b1.Property<double>("Y")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("float")
                                .HasDefaultValue(0.0)
                                .HasColumnName("Y");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Size", "VttTools.Data.Library.Entities.EncounterAsset.Size#NamedSize", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Height")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("float")
                                .HasDefaultValue(1.0)
                                .HasColumnName("Height");

                            b1.Property<double>("Width")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("float")
                                .HasDefaultValue(1.0)
                                .HasColumnName("Width");
                        });

                    b.HasKey("EncounterId", "Index");

                    b.HasIndex("AssetId");

                    b.HasIndex("ImageId");

                    b.ToTable("EncounterAssets", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.EncounterLight", b =>
                {
                    b.Property<Guid>("EncounterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<float?>("Arc")
                        .HasColumnType("real");

                    b.Property<string>("Color")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<float?>("Direction")
                        .HasColumnType("real");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<float>("Range")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Natural");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Position", "VttTools.Data.Library.Entities.EncounterLight.Position#Point", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("X")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("float")
                                .HasDefaultValue(0.0)
                                .HasColumnName("X");

                            b1.Property<double>("Y")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("float")
                                .HasDefaultValue(0.0)
                                .HasColumnName("Y");
                        });

                    b.HasKey("EncounterId", "Index");

                    b.HasIndex("EncounterId");

                    b.ToTable("EncounterLights", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.EncounterRegion", b =>
                {
                    b.Property<Guid>("EncounterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Elevation");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("EncounterId", "Index");

                    b.HasIndex("EncounterId");

                    b.ToTable("EncounterRegions", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.EncounterSound", b =>
                {
                    b.Property<Guid>("EncounterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPlaying")
                        .HasColumnType("bit");

                    b.Property<bool>("Loop")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<float>("Range")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Position", "VttTools.Data.Library.Entities.EncounterSound.Position#Point", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("X")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("float")
                                .HasDefaultValue(0.0)
                                .HasColumnName("X");

                            b1.Property<double>("Y")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("float")
                                .HasDefaultValue(0.0)
                                .HasColumnName("Y");
                        });

                    b.HasKey("EncounterId", "Index");

                    b.HasIndex("EncounterId");

                    b.HasIndex("ResourceId");

                    b.ToTable("EncounterSounds", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.EncounterWall", b =>
                {
                    b.Property<Guid>("EncounterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.HasKey("EncounterId", "Index");

                    b.HasIndex("EncounterId");

                    b.ToTable("EncounterWalls", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.EncounterWallSegment", b =>
                {
                    b.Property<Guid>("EncounterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("WallIndex")
                        .HasColumnType("bigint");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsOpaque")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Open");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Wall");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "EndPole", "VttTools.Data.Library.Entities.EncounterWallSegment.EndPole#Pole", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("H")
                                .HasColumnType("float")
                                .HasColumnName("EndH");

                            b1.Property<double>("X")
                                .HasColumnType("float")
                                .HasColumnName("EndX");

                            b1.Property<double>("Y")
                                .HasColumnType("float")
                                .HasColumnName("EndY");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "StartPole", "VttTools.Data.Library.Entities.EncounterWallSegment.StartPole#Pole", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("H")
                                .HasColumnType("float")
                                .HasColumnName("StartH");

                            b1.Property<double>("X")
                                .HasColumnType("float")
                                .HasColumnName("StartX");

                            b1.Property<double>("Y")
                                .HasColumnType("float")
                                .HasColumnName("StartY");
                        });

                    b.HasKey("EncounterId", "WallIndex", "Index");

                    b.HasIndex("EncounterId");

                    b.ToTable("EncounterWallSegments", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.World", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BackgroundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundId");

                    b.ToTable("Worlds", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Maintenance.Entities.MaintenanceMode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("DATETIME2");

                    b.Property<Guid?>("DisabledBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EnabledAt")
                        .HasColumnType("DATETIME2");

                    b.Property<Guid?>("EnabledBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ScheduledEndTime")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime?>("ScheduledStartTime")
                        .HasColumnType("DATETIME2");

                    b.HasKey("Id");

                    b.HasIndex("EnabledBy");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("ScheduledEndTime");

                    b.HasIndex("ScheduledStartTime");

                    b.HasIndex("IsEnabled", "ScheduledStartTime");

                    b.ToTable("MaintenanceMode", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Media.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<TimeSpan>("Duration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time")
                        .HasDefaultValue(new TimeSpan(0, 0, 0, 0, 0));

                    b.Property<decimal>("FileLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasDefaultValue(0m);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("Undefined");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ResourceType");

                    b.HasIndex("IsPublic", "IsPublished");

                    b.HasIndex("OwnerId", "ResourceType");

                    b.HasIndex("Path", "FileName");

                    b.ToTable("Resources", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.Media.Entities.ResourceFeature", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("ResourceId", "Key", "Index");

                    b.ToTable("ResourceFeatures", (string)null);
                });

            modelBuilder.Entity("VttTools.Identity.Model.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("019639ea-c7de-7e6f-b549-baf14386ad2f"),
                            ConcurrencyStamp = "b62e16a3-1d3a-4ae3-8c30-9bc628231f7a",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = new Guid("019639ea-c7de-786f-9f95-b397ca9509df"),
                            ConcurrencyStamp = "11d8a8d1-3a54-4464-890f-5e8c71b46c0b",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("VttTools.Identity.Model.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("VttTools.Identity.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("AvatarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("UnitSystem")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("019639ea-c7de-7a01-8548-41edfccde206"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "54c61fbd-4b9f-4a08-a6ce-c46443f8afb8",
                            DisplayName = "Master",
                            Email = "master@host.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Master",
                            NormalizedEmail = "MASTER@HOST.COM",
                            NormalizedUserName = "MASTER@HOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGCIPOjKQsg/WIuLEYnhnyHOsif13MaeUlO0J2ZVkMe41HuVFCqudWtLqGMKQXNBNA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "QAZB7SA3GUP4I2DQCDEDORPB5Q5ICUQG",
                            TwoFactorEnabled = false,
                            UnitSystem = 0,
                            UserName = "master@host.com"
                        });
                });

            modelBuilder.Entity("VttTools.Identity.Model.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("VttTools.Identity.Model.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("VttTools.Identity.Model.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("019639ea-c7de-7a01-8548-41edfccde206"),
                            RoleId = new Guid("019639ea-c7de-7e6f-b549-baf14386ad2f")
                        });
                });

            modelBuilder.Entity("VttTools.Identity.Model.UserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("VttTools.Data.AI.Entities.AiModel", b =>
                {
                    b.HasOne("VttTools.Data.AI.Entities.Provider", "Provider")
                        .WithMany("Models")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("VttTools.Data.AI.Entities.PromptTemplate", b =>
                {
                    b.HasOne("VttTools.Data.Media.Entities.Resource", "ReferenceImage")
                        .WithMany()
                        .HasForeignKey("ReferenceImageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ReferenceImage");
                });

            modelBuilder.Entity("VttTools.Data.Assets.Entities.Asset", b =>
                {
                    b.HasOne("VttTools.Data.Media.Entities.Resource", "Portrait")
                        .WithMany()
                        .HasForeignKey("PortraitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("VttTools.Common.Model.NamedSize", "TokenSize", b1 =>
                        {
                            b1.Property<Guid>("AssetId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Height")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("float")
                                .HasDefaultValue(0.0)
                                .HasColumnName("Height");

                            b1.Property<double>("Width")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("float")
                                .HasDefaultValue(0.0)
                                .HasColumnName("Width");

                            b1.HasKey("AssetId");

                            b1.ToTable("Assets");

                            b1.WithOwner()
                                .HasForeignKey("AssetId");
                        });

                    b.Navigation("Portrait");

                    b.Navigation("TokenSize")
                        .IsRequired();
                });

            modelBuilder.Entity("VttTools.Data.Assets.Entities.AssetStatBlockValue", b =>
                {
                    b.HasOne("VttTools.Data.Assets.Entities.Asset", "Asset")
                        .WithMany("StatBlock")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("VttTools.Data.Assets.Entities.AssetToken", b =>
                {
                    b.HasOne("VttTools.Data.Assets.Entities.Asset", "Asset")
                        .WithMany("AssetTokens")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VttTools.Data.Media.Entities.Resource", "Token")
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("VttTools.Data.Game.Entities.GameSession", b =>
                {
                    b.OwnsMany("VttTools.Data.Game.Entities.Participant", "Players", b1 =>
                        {
                            b1.Property<Guid>("GameSessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("bit");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.HasKey("GameSessionId", "UserId");

                            b1.ToTable("Players", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GameSessionId");
                        });

                    b.OwnsMany("VttTools.Data.Game.Entities.GameSessionEvent", "Events", b1 =>
                        {
                            b1.Property<Guid>("GameSessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("Timestamp")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("nvarchar(1024)");

                            b1.HasKey("GameSessionId", "Timestamp");

                            b1.ToTable("Events", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GameSessionId");
                        });

                    b.OwnsMany("VttTools.Data.Game.Entities.GameSessionMessage", "Messages", b1 =>
                        {
                            b1.Property<Guid>("GameSessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("SentAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(4096)
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("SentBy")
                                .HasColumnType("uniqueidentifier");

                            b1.PrimitiveCollection<string>("SentTo")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.HasKey("GameSessionId", "SentAt");

                            b1.ToTable("Messages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GameSessionId");
                        });

                    b.Navigation("Events");

                    b.Navigation("Messages");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("VttTools.Data.Game.Entities.Schedule", b =>
                {
                    b.OwnsMany("VttTools.Data.Game.Entities.Participant", "Participants", b1 =>
                        {
                            b1.Property<Guid>("ScheduleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("bit");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.HasKey("ScheduleId", "UserId");

                            b1.ToTable("Participants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ScheduleId");
                        });

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("VttTools.Data.Jobs.Entities.JobItem", b =>
                {
                    b.HasOne("VttTools.Data.Jobs.Entities.Job", "Job")
                        .WithMany("Items")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.Adventure", b =>
                {
                    b.HasOne("VttTools.Data.Media.Entities.Resource", "Background")
                        .WithMany()
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VttTools.Data.Library.Entities.Campaign", "Campaign")
                        .WithMany("Adventures")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VttTools.Data.Library.Entities.World", "World")
                        .WithMany("Adventures")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Background");

                    b.Navigation("Campaign");

                    b.Navigation("World");
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.Campaign", b =>
                {
                    b.HasOne("VttTools.Data.Media.Entities.Resource", "Background")
                        .WithMany()
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VttTools.Data.Library.Entities.World", "World")
                        .WithMany("Campaigns")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Background");

                    b.Navigation("World");
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.Encounter", b =>
                {
                    b.HasOne("VttTools.Data.Library.Entities.Adventure", "Adventure")
                        .WithMany("Encounters")
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VttTools.Data.Media.Entities.Resource", "AmbientSound")
                        .WithMany()
                        .HasForeignKey("AmbientSoundId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VttTools.Data.Media.Entities.Resource", "Background")
                        .WithMany()
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Adventure");

                    b.Navigation("AmbientSound");

                    b.Navigation("Background");
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.EncounterAsset", b =>
                {
                    b.HasOne("VttTools.Data.Assets.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VttTools.Data.Library.Entities.Encounter", "Encounter")
                        .WithMany("EncounterAssets")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VttTools.Data.Media.Entities.Resource", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("Encounter");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.EncounterLight", b =>
                {
                    b.HasOne("VttTools.Data.Library.Entities.Encounter", "Encounter")
                        .WithMany("LightSources")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.EncounterRegion", b =>
                {
                    b.HasOne("VttTools.Data.Library.Entities.Encounter", "Encounter")
                        .WithMany("Regions")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("VttTools.Common.Model.Point", "Vertices", b1 =>
                        {
                            b1.Property<Guid>("EncounterRegionEncounterId");

                            b1.Property<long>("EncounterRegionIndex");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<double>("X");

                            b1.Property<double>("Y");

                            b1.HasKey("EncounterRegionEncounterId", "EncounterRegionIndex", "__synthesizedOrdinal");

                            b1.ToTable("EncounterRegions");

                            b1.ToJson("Vertices");

                            b1.WithOwner()
                                .HasForeignKey("EncounterRegionEncounterId", "EncounterRegionIndex");
                        });

                    b.Navigation("Encounter");

                    b.Navigation("Vertices");
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.EncounterSound", b =>
                {
                    b.HasOne("VttTools.Data.Library.Entities.Encounter", "Encounter")
                        .WithMany("SoundSources")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VttTools.Data.Media.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Encounter");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.EncounterWall", b =>
                {
                    b.HasOne("VttTools.Data.Library.Entities.Encounter", "Encounter")
                        .WithMany("Walls")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.EncounterWallSegment", b =>
                {
                    b.HasOne("VttTools.Data.Library.Entities.EncounterWall", "Wall")
                        .WithMany("Segments")
                        .HasForeignKey("EncounterId", "WallIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wall");
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.World", b =>
                {
                    b.HasOne("VttTools.Data.Media.Entities.Resource", "Background")
                        .WithMany()
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Background");
                });

            modelBuilder.Entity("VttTools.Data.Media.Entities.Resource", b =>
                {
                    b.OwnsOne("VttTools.Common.Model.Size", "Size", b1 =>
                        {
                            b1.Property<Guid>("ResourceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Height")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Height");

                            b1.Property<int>("Width")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Width");

                            b1.HasKey("ResourceId");

                            b1.ToTable("Resources");

                            b1.WithOwner()
                                .HasForeignKey("ResourceId");
                        });

                    b.OwnsOne("VttTools.Data.Media.Entities.ResourceClassification", "Classification", b1 =>
                        {
                            b1.Property<Guid>("ResourceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("Category");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("Kind");

                            b1.Property<string>("Subtype")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("Subtype");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("Type");

                            b1.HasKey("ResourceId");

                            b1.ToTable("Resources");

                            b1.WithOwner()
                                .HasForeignKey("ResourceId");
                        });

                    b.Navigation("Classification")
                        .IsRequired();

                    b.Navigation("Size")
                        .IsRequired();
                });

            modelBuilder.Entity("VttTools.Data.Media.Entities.ResourceFeature", b =>
                {
                    b.HasOne("VttTools.Data.Media.Entities.Resource", "Resource")
                        .WithMany("Features")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("VttTools.Identity.Model.RoleClaim", b =>
                {
                    b.HasOne("VttTools.Identity.Model.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VttTools.Identity.Model.UserClaim", b =>
                {
                    b.HasOne("VttTools.Identity.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VttTools.Identity.Model.UserLogin", b =>
                {
                    b.HasOne("VttTools.Identity.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VttTools.Identity.Model.UserRole", b =>
                {
                    b.HasOne("VttTools.Identity.Model.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VttTools.Identity.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VttTools.Identity.Model.UserToken", b =>
                {
                    b.HasOne("VttTools.Identity.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VttTools.Data.AI.Entities.Provider", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("VttTools.Data.Assets.Entities.Asset", b =>
                {
                    b.Navigation("AssetTokens");

                    b.Navigation("StatBlock");
                });

            modelBuilder.Entity("VttTools.Data.Jobs.Entities.Job", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.Adventure", b =>
                {
                    b.Navigation("Encounters");
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.Campaign", b =>
                {
                    b.Navigation("Adventures");
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.Encounter", b =>
                {
                    b.Navigation("EncounterAssets");

                    b.Navigation("LightSources");

                    b.Navigation("Regions");

                    b.Navigation("SoundSources");

                    b.Navigation("Walls");
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.EncounterWall", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("VttTools.Data.Library.Entities.World", b =>
                {
                    b.Navigation("Adventures");

                    b.Navigation("Campaigns");
                });

            modelBuilder.Entity("VttTools.Data.Media.Entities.Resource", b =>
                {
                    b.Navigation("Features");
                });
#pragma warning restore 612, 618
        }
    }
}
