// <auto-generated />
#nullable disable

namespace VttTools.Data.MigrationService.Migrations;

/// <inheritdoc />
public partial class UpdateResourcePropertiesName : Migration {
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder) {
        migrationBuilder.DropForeignKey(
            name: "FK_Effects_Resources_ResourceId",
            table: "Effects");

        migrationBuilder.RenameColumn(
            name: "ResourceId",
            table: "Effects",
            newName: "ImageId");

        migrationBuilder.RenameIndex(
            name: "IX_Effects_ResourceId",
            newName: "IX_Effects_ImageId",
            table: "Effects");

        migrationBuilder.RenameColumn(
            name: "ResourceId",
            table: "Epics",
            newName: "BackgroundId");

        migrationBuilder.AlterColumn<Guid>(
            name: "BackgroundId",
            table: "Epics",
            type: "uniqueidentifier",
            nullable: true,
            oldClrType: typeof(Guid),
            oldType: "uniqueidentifier");

        migrationBuilder.RenameColumn(
            name: "ResourceId",
            table: "Campaigns",
            newName: "BackgroundId");

        migrationBuilder.AlterColumn<Guid>(
            name: "BackgroundId",
            table: "Campaigns",
            type: "uniqueidentifier",
            nullable: true,
            oldClrType: typeof(Guid),
            oldType: "uniqueidentifier");

        migrationBuilder.AddForeignKey(
            name: "FK_Effects_Resources_ImageId",
            table: "Effects",
            column: "ImageId",
            principalTable: "Resources",
            principalColumn: "Id",
            onDelete: ReferentialAction.Restrict);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder) {
        migrationBuilder.DropForeignKey(
            name: "FK_Effects_Resources_ImageId",
            table: "Effects");

        migrationBuilder.RenameColumn(
            name: "ImageId",
            table: "Effects",
            newName: "ResourceId");

        migrationBuilder.RenameIndex(
            name: "IX_Effects_ImageId",
            newName: "IX_Effects_ResourceId",
            table: "Effects");

        migrationBuilder.AlterColumn<Guid>(
            name: "BackgroundId",
            table: "Epics",
            type: "uniqueidentifier",
            nullable: false,
            defaultValue: new Guid("00000000-0000-0000-0000-000000000000"),
            oldClrType: typeof(Guid),
            oldType: "uniqueidentifier",
            oldNullable: true);

        migrationBuilder.RenameColumn(
            name: "BackgroundId",
            table: "Epics",
            newName: "ResourceId");

        migrationBuilder.AlterColumn<Guid>(
            name: "BackgroundId",
            table: "Campaigns",
            type: "uniqueidentifier",
            nullable: false,
            defaultValue: new Guid("00000000-0000-0000-0000-000000000000"),
            oldClrType: typeof(Guid),
            oldType: "uniqueidentifier",
            oldNullable: true);

        migrationBuilder.RenameColumn(
            name: "BackgroundId",
            table: "Campaigns",
            newName: "ResourceId");

        migrationBuilder.AddForeignKey(
            name: "FK_Effects_Resources_ResourceId",
            table: "Effects",
            column: "BackgroundId",
            principalTable: "Resources",
            principalColumn: "Id",
            onDelete: ReferentialAction.SetNull);
    }
}
