// <auto-generated />
#nullable disable

namespace VttTools.Data.MigrationService.Migrations;

/// <inheritdoc />
public partial class SeedApplicationSchema : Migration {
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder) {
        migrationBuilder.InsertData(
            table: "Resources",
            columns: ["Id", "OwnerId", "ResourceType", "Kind", "Category", "Type", "Subtype", "ContentType", "Path", "FileName", "FileLength", "Duration", "Height", "Width"],
            values: new object[,]
            {
                { new Guid("019A50F8-F3E5-702B-89D3-33D694391F66"), new Guid("019639EA-C7DE-7A01-8548-41EDFCCDE206"), "Token", "Object", "Container", "Storage", null, "image/png", "images/1f66/019a50f8f3e5702b89d333d694391f66", "wooden-crate.png", 1170, "00:00:00.0000000", 200, 200 },
                { new Guid("019A50CE-4B04-7378-8E6E-372BDF798985"), new Guid("019639EA-C7DE-7A01-8548-41EDFCCDE206"), "Token", "Creature", "Monster", "Fey", "Goblinoid", "image/png", "images/8985/019a50ce4b0473788e6e372bdf798985", "goblin.png", 8193, "00:00:00.0000000", 200, 200 },
                { new Guid("019A50F8-394B-79D2-9660-9B803391DD71"), new Guid("019639EA-C7DE-7A01-8548-41EDFCCDE206"), "Token", "Character", "Elf", "Paladin", null, "image/png", "images/dd71/019a50f8394b79d296609b803391dd71", "hero-character.png", 6821, "00:00:00.0000000", 200, 200 },
                { new Guid("019A50F8-AF0E-7EDE-BBAB-C1AA0775FA86"), new Guid("019639EA-C7DE-7A01-8548-41EDFCCDE206"), "Token", "Object", "Container", "Storage", null, "image/png", "images/fa86/019a50f8af0e7edebbabc1aa0775fa86", "treasure-chest.png", 2286, "00:00:00.0000000", 200, 200 },
                { new Guid("019ACE1D-5B91-72D1-8D9F-70640D3DBFE1"), new Guid("019639EA-C7DE-7A01-8548-41EDFCCDE206"), "Background", "Map", "Encounter", "House", "Interior", "image/png", "images/bfe1/019ace1d5b9172d18d9f70640d3dbfe1", "The_Nesti.png", 1394149, "00:00:00.0000000", 1026, 972 },
                { new Guid("019b0192-ca87-7ae6-9e0b-fb23c2c71995"), new Guid("019639ea-c7de-7a01-8548-41edfccde206"), "AmbientSound", "", "", "", null, "audio/ogg", "audio/1995/019b0192ca877ae69e0bfb23c2c71995", "file_example_MP3_700KB.ogg", 399753, "00:00:42.0080000", 0, 0},
            });

        migrationBuilder.InsertData(
            table: "Worlds",
            columns: ["Id", "OwnerId", "Name", "Description", "BackgroundId", "IsPublished", "IsPublic"],
            values: new object[,]
            {
                { new Guid("019A1480-D106-7627-8394-1F2A607AB656"), new Guid("019639EA-C7DE-7A01-8548-41EDFCCDE206"), "Untitled World", "A new world.", null, false, false },
            });

        migrationBuilder.InsertData(
            table: "Campaigns",
            columns: ["Id", "WorldId", "OwnerId", "Name", "Description", "BackgroundId", "IsPublished", "IsPublic"],
            values: new object[,]
            {
                { new Guid("019A1480-D107-7627-8394-1F2A607AB656"), null, new Guid("019639EA-C7DE-7A01-8548-41EDFCCDE206"), "Untitled Campaign", "A new campaign.", null, false, false },
            });

        migrationBuilder.InsertData(
            table: "Adventures",
            columns: ["Id", "WorldId", "CampaignId", "OwnerId", "Name", "Style", "Description", "BackgroundId", "IsOneShot", "IsPublished", "IsPublic"],
            values: new object[,]
            {
                { new Guid("019A1480-D108-7627-8394-1F2A607AB656"), null, null, new Guid("019639EA-C7DE-7A01-8548-41EDFCCDE206"), "My Adventure", "OpenWorld", "My new adventure.", null, true, false, false },
                { new Guid("019A1488-D51D-7B45-A579-FA2D31F118B3"), null, null, new Guid("019639EA-C7DE-7A01-8548-41EDFCCDE206"), "Untitled Adventure", "Generic", "A new adventure.", null, false, false, false }
            });

        migrationBuilder.InsertData(
            table: "Encounters",
            columns: ["Id", "AdventureId", "Name", "Description", "IsPublished", "ZoomLevel", "BackgroundId", "GridType", "GridCellHeight", "GridCellWidth", "GridOffsetLeft", "GridOffsetTop", "PanningX", "PanningY"],
            values: new object[,]
            {
                { new Guid("019A26C8-0DF8-7BED-A5D5-12C035B72F91"), new Guid("019A1480-D108-7627-8394-1F2A607AB656"), "The Tavern", "Hello", false, 1, null, "Square", 50, 50, 0, 0, 0, 0 },
                { new Guid("019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C"), new Guid("019A1480-D108-7627-8394-1F2A607AB656"), "The Nesti", "", false, 1, new Guid("019ACE1D-5B91-72D1-8D9F-70640D3DBFE1"), "Square", 53.75, 53.75, 1, 3, 0, 0 },
            });

        migrationBuilder.Sql(
            """
            INSERT INTO [Assets] ([Id], [OwnerId], [Kind], [Category], [Type], [Subtype], [Name], [Description], [Tags], [PortraitId], [IsPublished], [IsPublic], [Height], [Width])
            VALUES
            ('019A07E4-ECBC-7F23-B6C9-26A7D72AC421', '019639EA-C7DE-7A01-8548-41EDFCCDE206', 'Object'   , 'Container', 'Storage', NULL, 'Create, Small', '', '[]', '019A50F8-F3E5-702B-89D3-33D694391F66', 0, 0, 0.5, 0.5),
            ('019A0363-E277-7FA4-9A78-654F24400B79', '019639EA-C7DE-7A01-8548-41EDFCCDE206', 'Creature' , 'Monster', 'Fey', 'Goblinoid', 'Goblin Warrior', '', '[]', '019A50CE-4B04-7378-8E6E-372BDF798985', 1, 1, 1.0, 1.0),
            ('019A07E6-82A2-7286-ACAB-7CCB6CF652BD', '019639EA-C7DE-7A01-8548-41EDFCCDE206', 'Object'   , 'Container', 'Storage', NULL, 'Chest, Wide', '', '[]', '019A50F8-AF0E-7EDE-BBAB-C1AA0775FA86', 0, 0, 1.0, 2.0),
            ('019A07E5-5550-7993-9B0B-84244F1543DF', '019639EA-C7DE-7A01-8548-41EDFCCDE206', 'Object'   , 'Container', 'Storage', NULL, 'Create, Large', '', '[]', '019A50F8-F3E5-702B-89D3-33D694391F66', 0, 0, 2.0, 2.0),
            ('019A0363-9294-749D-9323-B759664A5436', '019639EA-C7DE-7A01-8548-41EDFCCDE206', 'Object'   , 'Container', 'Storage', NULL, 'Create', '', '[]', '019A50F8-F3E5-702B-89D3-33D694391F66', 0, 0, 1.0, 1.0),
            ('019A2B1B-25CF-74A7-B1C3-C9F46CBFB9FA', '019639EA-C7DE-7A01-8548-41EDFCCDE206', 'Character', 'Elf', 'Paladin', 'Squire', 'Sir Pelotas', '', '[]', '019A50F8-394B-79D2-9660-9B803391DD71', 1, 1, 1.0, 1.0);
            """
        );

        migrationBuilder.Sql(
            """
            INSERT INTO [EncounterRegions] ([EncounterId], [Index], [Name], [Type], [Value], [Vertices])
            VALUES
            ('019A26C8-0DF8-7BED-A5D5-12C035B72F91', 0, 'Region 1', 'Elevation', 0, '[{"X":22,"Y":15},{"X":25,"Y":19.5},{"X":31.5,"Y":19.5},{"X":33,"Y":14}]'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 0, 'Region 1', 'Elevation', 10, '[{"X":4,"Y":11},{"X":4,"Y":13},{"X":3.5,"Y":13},{"X":3.5,"Y":15},{"X":5,"Y":15},{"X":5,"Y":16},{"X":7,"Y":16},{"X":7,"Y":11}]'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 1, 'Region 2', 'Elevation', 20, '[{"X":11.5,"Y":14},{"X":11.5,"Y":15},{"X":12.5,"Y":15},{"X":12.5,"Y":16},{"X":13.5,"Y":16},{"X":13.5,"Y":14}]');
            """
        );

        migrationBuilder.Sql(
            """
            INSERT INTO [EncounterWalls] ([EncounterId], [Index])
            VALUES
            ('019A26C8-0DF8-7BED-A5D5-12C035B72F91', 0),
            ('019A26C8-0DF8-7BED-A5D5-12C035B72F91', 1),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 0),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 1),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 2),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 3);
            """
        );

        migrationBuilder.Sql(
            """
            INSERT INTO [EncounterWallSegments] ([EncounterId], [WallIndex], [Index], [Name], [Type], [IsOpaque], [StartX], [StartY], [StartH], [EndX], [EndY], [EndH], [State])
            VALUES
            ('019A26C8-0DF8-7BED-A5D5-12C035B72F91', 0,  0, 'Wall', 'Wall', 1,   35.00, 15.00, 10, 31.50, 20.50, 10, 'Visible'),
            ('019A26C8-0DF8-7BED-A5D5-12C035B72F91', 0,  1, 'Wall', 'Wall', 1,   31.50, 20.50, 10, 23.00, 20.50, 10, 'Visible'),
            ('019A26C8-0DF8-7BED-A5D5-12C035B72F91', 0,  2, 'Wall', 'Wall', 1,   23.00, 20.50, 10, 30.00, 15.50, 10, 'Visible'),
            ('019A26C8-0DF8-7BED-A5D5-12C035B72F91', 1,  0, 'Wall', 'Wall', 1,   36.00, 15.50, 10, 36.00, 17.50, 10, 'Visible'),
            ('019A26C8-0DF8-7BED-A5D5-12C035B72F91', 1,  1, 'Wall', 'Wall', 1,   36.00, 17.50, 10, 38.00, 17.50, 10, 'Visible'),
            ('019A26C8-0DF8-7BED-A5D5-12C035B72F91', 1,  2, 'Wall', 'Wall', 1,   38.00, 17.50, 10, 38.00, 15.50, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 0,  0, 'Wall', 'Wall', 1,    5.00, 15.00, 10,  3.50, 15.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 0,  1, 'Wall', 'Wall', 1,    3.50, 15.00, 10,  3.50, 14.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 0,  2, 'Window #1', 'Window', 1,  3.50, 14.00, 10,  3.50, 13.50, 10, 'Closed'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 0,  3, 'Wall', 'Wall', 1,    3.50, 13.50, 10,  3.50, 13.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 0,  4, 'Wall', 'Wall', 1,    3.50, 13.00, 10,  4.00, 13.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 0,  5, 'Wall', 'Wall', 1,    4.00, 13.00, 10,  4.00, 11.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 0,  6, 'Wall', 'Wall', 1,    4.00, 11.00, 10,  4.25, 11.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 0,  7, 'Window #2', 'Window', 1,  4.25, 11.00, 10,  4.82, 11.00, 10, 'Closed'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 0,  8, 'Wall', 'Wall', 1,    4.82, 11.00, 10,  6.20, 11.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 0,  9, 'Window #3', 'Window', 1,  6.20, 11.00, 10,  6.79, 11.00, 10, 'Closed'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 0, 10, 'Wall', 'Wall', 1,    6.79, 11.00, 10,  7.00, 11.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 0, 11, 'Wall', 'Wall', 1,    7.00, 11.00, 10,  7.00, 14.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 0, 12, 'Door #1', 'Door', 1,    7.00, 14.00, 10,  7.00, 15.00, 10, 'Closed'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 0, 13, 'Wall', 'Wall', 1,    7.00, 15.00, 10,  7.00, 16.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 0, 14, 'Wall', 'Wall', 1,    7.00, 16.00, 10,  6.32, 16.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 0, 15, 'Window #4', 'Window', 1,  6.32, 16.00, 10,  5.75, 16.00, 10, 'Closed'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 0, 16, 'Wall', 'Wall', 1,    5.75, 16.00, 10,  5.00, 16.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 0, 17, 'Wall', 'Wall', 1,    5.00, 16.00, 10,  5.00, 15.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 1,  0, 'Wall', 'Wall', 1,   11.50, 14.00, 10, 12.76, 14.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 1,  1, 'Window #5', 'Window', 1, 12.76, 14.00, 10, 13.23, 14.00, 10, 'Closed'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 1,  2, 'Wall', 'Wall', 1,   13.23, 14.00, 10, 13.50, 14.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 1,  3, 'Wall', 'Wall', 1,   13.50, 14.00, 10, 13.50, 16.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 1,  4, 'Wall', 'Wall', 1,   13.50, 16.00, 10, 12.50, 16.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 1,  5, 'Wall', 'Wall', 1,   12.50, 16.00, 10, 12.50, 15.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 1,  6, 'Wall', 'Wall', 1,   12.50, 15.00, 10, 11.50, 15.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 1,  7, 'Wall', 'Wall', 1,   11.50, 15.00, 10, 11.50, 14.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 2,  0, 'Wall', 'Wall', 1,    4.00,  3.00, 10,  4.00,  5.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 2,  1, 'Wall', 'Wall', 1,    4.00,  5.00, 10,  3.50,  5.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 2,  2, 'Wall', 'Wall', 1,    3.50,  5.00, 10,  3.50,  5.27, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 2,  3, 'Window #6', 'Window', 1,  3.50,  5.27, 10,  3.50,  5.83, 10, 'Closed'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 2,  4, 'Wall', 'Wall', 1,    3.50,  5.83, 10,  3.50,  6.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 2,  5, 'Wall', 'Wall', 1,    3.50,  6.00, 10,  3.00,  6.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 2,  6, 'Wall', 'Wall', 1,    3.00,  6.00, 10,  3.00,  7.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 2,  7, 'Wall', 'Wall', 1,    3.00,  7.00, 10,  5.54,  7.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 2,  8, 'Door #2', 'Door', 1,    5.54,  7.00, 10,  6.47,  7.00, 10, 'Closed'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 2,  9, 'Wall', 'Wall', 1,    6.47,  7.00, 10,  7.00,  7.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 2, 10, 'Wall', 'Wall', 1,    7.00,  7.00, 10,  7.00,  3.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 2, 11, 'Wall', 'Wall', 1,    7.00,  3.00, 10,  5.81,  3.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 2, 12, 'Window #7', 'Window', 1,  5.81,  3.00, 10,  5.20,  3.00, 10, 'Closed'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 2, 13, 'Wall', 'Wall',        1,  5.20,  3.00, 10,  4.00,  3.00, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 3,  0, 'Wall', 'Wall', 1,    5.00,  3.00, 10,  5.00,  4.50, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 3,  1, 'Wall', 'Wall', 1,    5.00,  4.50, 10,  5.22,  4.50, 10, 'Visible'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 3,  2, 'Passage #1', 'Door', 0,   5.22,  4.50, 10,  5.80,  4.50, 10, 'Open'),
            ('019ACE1D-3C6A-7FEA-84DC-62CC6C4CBB4C', 3,  3, 'Wall', 'Wall', 1,    5.80,  4.50, 10,  7.00,  4.50, 10, 'Visible');
            """
        );

        migrationBuilder.Sql(
            """
            INSERT INTO [EncounterSounds] ([EncounterId], [Index], [Name], [Range], [IsPlaying], [Loop], [ResourceId], [X], [Y])
            VALUES
            ('019ace1d-3c6a-7fea-84dc-62cc6c4cbb4c', 0, 'Sound #1', 4, 0, 0, '019b0192-ca87-7ae6-9e0b-fb23c2c71995', 6.25, 5.75);
            """
        );

        migrationBuilder.Sql(
            """
            INSERT INTO [EncounterLights] ([EncounterId], [Index], [Name], [Type], [Range], [Direction], [Arc], [IsOn], [Color], [X], [Y])
            VALUES
            ('019ace1d-3c6a-7fea-84dc-62cc6c4cbb4c', 0, '', 'Natural', 4.5, NULL, NULL, 1, '', 4.5, 6.75);
            """
        );

        migrationBuilder.Sql(
            """
            INSERT INTO [EncounterAssets] ([EncounterId], [Index], [AssetId], [Name], [IsLocked], [IsVisible], [ImageId], [Rotation], [Elevation], [ControlledBy], [Notes], [FrameBackground], [FrameBorderColor], [FrameBorderThickness], [FrameShape], [X], [Y], [Height], [Width])
            VALUES
            ('019A26C8-0DF8-7BED-A5D5-12C035B72F91', 0, '019A0363-9294-749D-9323-B759664A5436', 'Wooden Create', 0, 1, '019A50F8-F3E5-702B-89D3-33D694391F66', 0, 0, '019639EA-C7DE-7A01-8548-41EDFCCDE206', NULL, '#00000000', '#0d6efd', 1, 'Square', 26.5, 22.5, 50, 50),
            ('019A26C8-0DF8-7BED-A5D5-12C035B72F91', 1, '019A07E6-82A2-7286-ACAB-7CCB6CF652BD', 'Wide Chest', 0, 1, '019A50F8-AF0E-7EDE-BBAB-C1AA0775FA86', 0, 0, '019639EA-C7DE-7A01-8548-41EDFCCDE206', NULL, '#00000000', '#0d6efd', 1, 'Square', 30, 21.5, 50, 100),
            ('019A26C8-0DF8-7BED-A5D5-12C035B72F91', 2, '019A0363-E277-7FA4-9A78-654F24400B79', 'Goblin #1', 0, 1, '019A50CE-4B04-7378-8E6E-372BDF798985', 0, 0, '019639EA-C7DE-7A01-8548-41EDFCCDE206', NULL, '#00000000', '#0d6efd', 1, 'Square', 33.5, 20.5, 50, 50),
            ('019A26C8-0DF8-7BED-A5D5-12C035B72F91', 3, '019A2B1B-25CF-74A7-B1C3-C9F46CBFB9FA', 'Elf Paladin Squire', 0, 1, '019A50F8-394B-79D2-9660-9B803391DD71', 0, 0, '019639EA-C7DE-7A01-8548-41EDFCCDE206', NULL, '#00000000', '#0d6efd', 1, 'Square', 21.5, 19.5, 50, 50),
            ('019ace1d-3c6a-7fea-84dc-62cc6c4cbb4c', 0, '019a0363-9294-749d-9323-b759664a5436', 'Create', 0, 1, '019a50f8-f3e5-702b-89d3-33d694391f66', 0, 0, '019639ea-c7de-7a01-8548-41edfccde206', NULL, '#00000000', '#0d6efd', 1, 'Square', 4.5, 5.5, 53.75, 53.75);
            """
        );
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder) {
        migrationBuilder.Sql(
            """
            DELETE FROM [EncounterAssets];
            """
        );

        migrationBuilder.Sql(
            """
            DELETE FROM [EncounterLights];
            """
        );

        migrationBuilder.Sql(
            """
            DELETE FROM [EncounterSounds];
            """
        );

        migrationBuilder.Sql(
            """
            DELETE FROM [EncounterWallSegments];
            """
        );

        migrationBuilder.Sql(
            """
            DELETE FROM [EncounterWalls];
            """
        );

        migrationBuilder.Sql(
            """
            DELETE FROM [EncounterRegions];
            """
        );

        migrationBuilder.Sql(
            """
            DELETE FROM [Assets];
            """
        );

        migrationBuilder.Sql(
            """
            DELETE FROM [Encounters];
            """
        );

        migrationBuilder.Sql(
            """
            DELETE FROM [Adventures];
            """
        );

        migrationBuilder.Sql(
            """
            DELETE FROM [Campaigns];
            """
        );

        migrationBuilder.Sql(
            """
            DELETE FROM [Worlds];
            """
        );

        migrationBuilder.Sql(
            """
            DELETE FROM [Resources];
            """
        );
    }
}
