// <auto-generated />
#nullable disable

namespace VttTools.Data.MigrationService.Migrations;

/// <inheritdoc />
public partial class SeedApplicationSchema : Migration {
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder) {
        migrationBuilder.InsertData(
            table: "Resources",
            columns: ["Id", "Type", "ContentType", "Path", "FileName", "FileLength", "Duration", "Tags", "ImageSize_Height", "ImageSize_Width"],
            values: new object[,]
            {
                { new Guid("019A50F8-F3E5-702B-89D3-33D694391F66"), "Image", "image/png", "images/1f66/019a50f8f3e5702b89d333d694391f66", "wooden-crate.png", 1170, "00:00:00.0000000", "[]", 200, 200 },
                { new Guid("019A50CE-4B04-7378-8E6E-372BDF798985"), "Image", "image/png", "images/8985/019a50ce4b0473788e6e372bdf798985", "goblin.png", 8193, "00:00:00.0000000", "[]", 200, 200 },
                { new Guid("019A50F8-394B-79D2-9660-9B803391DD71"), "Image", "image/png", "images/dd71/019a50f8394b79d296609b803391dd71", "hero-character.png", 6821, "00:00:00.0000000", "[]", 200, 200 },
                { new Guid("019A50F8-AF0E-7EDE-BBAB-C1AA0775FA86"), "Image", "image/png", "images/fa86/019a50f8af0e7edebbabc1aa0775fa86", "treasure-chest.png", 2286, "00:00:00.0000000", "[]", 200, 200 },
            });

        migrationBuilder.InsertData(
            table: "Worlds",
            columns: ["Id", "OwnerId", "Name", "Description", "BackgroundId", "IsPublished", "IsPublic"],
            values: new object[,]
            {
                { new Guid("019A1480-D106-7627-8394-1F2A607AB656"), new Guid("019639EA-C7DE-7A01-8548-41EDFCCDE206"), "Untitled World", "A new world.", null, false, false },
            });

        migrationBuilder.InsertData(
            table: "Campaigns",
            columns: ["Id", "WorldId", "OwnerId", "Name", "Description", "BackgroundId", "IsPublished", "IsPublic"],
            values: new object[,]
            {
                { new Guid("019A1480-D107-7627-8394-1F2A607AB656"), null, new Guid("019639EA-C7DE-7A01-8548-41EDFCCDE206"), "Untitled Campaign", "A new campaign.", null, false, false },
            });

        migrationBuilder.InsertData(
            table: "Adventures",
            columns: ["Id", "WorldId", "CampaignId", "OwnerId", "Name", "Style", "Description", "BackgroundId", "IsOneShot", "IsPublished", "IsPublic"],
            values: new object[,]
            {
                { new Guid("019A1480-D108-7627-8394-1F2A607AB656"), null, null, new Guid("019639EA-C7DE-7A01-8548-41EDFCCDE206"), "My Adventure", "OpenWorld", "My new adventure.", null, true, false, false },
                { new Guid("019A1488-D51D-7B45-A579-FA2D31F118B3"), null, null, new Guid("019639EA-C7DE-7A01-8548-41EDFCCDE206"), "Untitled Adventure", "Generic", "A new adventure.", null, false, false, false }
            });

        migrationBuilder.InsertData(
            table: "Encounters",
            columns: ["Id", "AdventureId", "Name", "Description", "IsPublished", "ZoomLevel", "BackgroundId", "Grid_Snap", "Grid_Type", "Grid_CellSize_Height", "Grid_CellSize_Width", "Grid_Offset_Left", "Grid_Offset_Top", "Panning_X", "Panning_Y"],
            values: new object[,]
            {
                { new Guid("019A26C8-0DF8-7BED-A5D5-12C035B72F91"), new Guid("019A1480-D108-7627-8394-1F2A607AB656"), "The Tavern (1)", "Hello", false, 1, null, true, "Square", 50, 50, 0, 0, 0, 0 }
            });

        migrationBuilder.Sql(
            """
            INSERT INTO [Assets] ([Id], [OwnerId], [Kind], [Name], [Description], [PortraitId], [IsPublished], [IsPublic], [Size_Height], [Size_Width], [StatBlockId], [Category], [TokenStyle_BorderColor], [TokenStyle_BackgroundColor], [TokenStyle_Shape], [IsMovable], [IsOpaque], [TriggerEffectId])
            VALUES
            ('019A07E4-ECBC-7F23-B6C9-26A7D72AC421', '019639EA-C7DE-7A01-8548-41EDFCCDE206', 'Object'  , 'Small Create'      , '', '019A50F8-F3E5-702B-89D3-33D694391F66', 0, 0, 0.5, 0.5, NULL, NULL       , NULL, NULL, NULL, 1   , 0   , NULL),
            ('019A0363-E277-7FA4-9A78-654F24400B79', '019639EA-C7DE-7A01-8548-41EDFCCDE206', 'Creature', 'Goblin'            , '', '019A50CE-4B04-7378-8E6E-372BDF798985', 1, 1, 1.0, 1.0, NULL, 'Monster'  , NULL, NULL, NULL, NULL, NULL, NULL),
            ('019A07E6-82A2-7286-ACAB-7CCB6CF652BD', '019639EA-C7DE-7A01-8548-41EDFCCDE206', 'Object'  , 'Wide Chest'        , '', '019A50F8-AF0E-7EDE-BBAB-C1AA0775FA86', 0, 0, 1.0, 2.0, NULL, NULL       , NULL, NULL, NULL, 1   , 0   , NULL),
            ('019A07E5-5550-7993-9B0B-84244F1543DF', '019639EA-C7DE-7A01-8548-41EDFCCDE206', 'Object'  , 'Large Create'      , '', '019A50F8-F3E5-702B-89D3-33D694391F66', 0, 0, 2.0, 2.0, NULL, NULL       , NULL, NULL, NULL, 1   , 0   , NULL),
            ('019A0363-9294-749D-9323-B759664A5436', '019639EA-C7DE-7A01-8548-41EDFCCDE206', 'Object'  , 'Wooden Create'     , '', '019A50F8-F3E5-702B-89D3-33D694391F66', 0, 0, 1.0, 1.0, NULL, NULL       , NULL, NULL, NULL, 1   , 0   , NULL),
            ('019A2B1B-25CF-74A7-B1C3-C9F46CBFB9FA', '019639EA-C7DE-7A01-8548-41EDFCCDE206', 'Creature', 'Elf Paladin Squire', '', '019A50F8-394B-79D2-9660-9B803391DD71', 1, 1, 1.0, 1.0, NULL, 'Character', NULL, NULL, NULL, NULL, NULL, NULL);
            """
        );

        migrationBuilder.InsertData(
            table: "AssetTokens",
            columns: ["AssetId", "TokenId", "IsDefault"],
            values: new object[,]
            {
                { new Guid("019A07E4-ECBC-7F23-B6C9-26A7D72AC421"), new Guid("019A50F8-F3E5-702B-89D3-33D694391F66"), 1 },
                { new Guid("019A0363-E277-7FA4-9A78-654F24400B79"), new Guid("019A50CE-4B04-7378-8E6E-372BDF798985"), 1 },
                { new Guid("019A07E6-82A2-7286-ACAB-7CCB6CF652BD"), new Guid("019A50F8-AF0E-7EDE-BBAB-C1AA0775FA86"), 1 },
                { new Guid("019A07E5-5550-7993-9B0B-84244F1543DF"), new Guid("019A50F8-F3E5-702B-89D3-33D694391F66"), 1 },
                { new Guid("019A0363-9294-749D-9323-B759664A5436"), new Guid("019A50F8-F3E5-702B-89D3-33D694391F66"), 1 },
                { new Guid("019A2B1B-25CF-74A7-B1C3-C9F46CBFB9FA"), new Guid("019A50F8-394B-79D2-9660-9B803391DD71"), 1 }
            });
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder) {
        migrationBuilder.DeleteData(
            table: "AssetTokens",
            keyColumns: ["AssetId", "TokenId"],
            keyValues: new object[,] {
                { new Guid("019A07E4-ECBC-7F23-B6C9-26A7D72AC421"), new Guid("019A50CD-4749-7C0E-B749-DF522061578E") },
                { new Guid("019A0363-E277-7FA4-9A78-654F24400B79"), new Guid("019A50CE-4B04-7378-8E6E-372BDF798985") },
                { new Guid("019A07E6-82A2-7286-ACAB-7CCB6CF652BD"), new Guid("019A50F8-AF0E-7EDE-BBAB-C1AA0775FA86") },
                { new Guid("019A07E5-5550-7993-9B0B-84244F1543DF"), new Guid("019A50F8-F3E5-702B-89D3-33D694391F66") },
                { new Guid("019A0363-9294-749D-9323-B759664A5436"), new Guid("019A50F9-3078-74F9-A8A2-B832E74EDC57") },
                { new Guid("019A2B1B-25CF-74A7-B1C3-C9F46CBFB9FA"), new Guid("019A50F8-394B-79D2-9660-9B803391DD71") }
            });

        migrationBuilder.DeleteData(
            table: "Assets",
            keyColumn: "Id",
            keyValues: [
                new Guid("019A07E4-ECBC-7F23-B6C9-26A7D72AC421"),
                new Guid("019A0363-E277-7FA4-9A78-654F24400B79"),
                new Guid("019A07E6-82A2-7286-ACAB-7CCB6CF652BD"),
                new Guid("019A07E5-5550-7993-9B0B-84244F1543DF"),
                new Guid("019A0363-9294-749D-9323-B759664A5436"),
                new Guid("019A2B1B-25CF-74A7-B1C3-C9F46CBFB9FA"),
            ]);

        migrationBuilder.DeleteData(
            table: "Encounters",
            keyColumn: "Id",
            keyValues: [
                new Guid("019A26C8-0DF8-7BED-A5D5-12C035B72F91"),
            ]);

        migrationBuilder.DeleteData(
            table: "Adventures",
            keyColumn: "Id",
            keyValues: [
                new Guid("019A1480-D108-7627-8394-1F2A607AB656"),
                new Guid("019A1488-D51D-7B45-A579-FA2D31F118B3")
            ]);

        migrationBuilder.DeleteData(
            table: "Resources",
            keyColumn: "Id",
            keyValues: [
                new Guid("019A50F8-F3E5-702B-89D3-33D694391F66"),
                new Guid("019A50CE-4B04-7378-8E6E-372BDF798985"),
                new Guid("019A50F8-394B-79D2-9660-9B803391DD71"),
                new Guid("019A50F9-3078-74F9-A8A2-B832E74EDC57"),
                new Guid("019A50F8-AF0E-7EDE-BBAB-C1AA0775FA86"),
                new Guid("019A50CD-4749-7C0E-B749-DF522061578E")
            ]);
    }
}
