// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace VttTools.Data.MigrationService.Migrations;

/// <inheritdoc />
public partial class SeedApplicationSchema : Migration {
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder) {
        migrationBuilder.InsertData(table: "Resources",
                                    columns: ["Id", "Path", "Type", "ContentType", "ImageSize_Height", "ImageSize_Width", "FileName", "FileLength"],
                                    values: new object[,] {
            { new Guid("17b7f449-b2eb-41b5-9bca-a25b431e5281"), "17b7f449-b2eb-41b5-9bca-a25b431e5281.png", "Image", "image/png", 720, 1024, "17b7f449-b2eb-41b5-9bca-a25b431e5281.png", 1500500 },
            { new Guid("1309dbfb-0721-4809-a0ae-173019591f85"), "1309dbfb-0721-4809-a0ae-173019591f85.png", "Image", "image/png", 2100, 2800, "1309dbfb-0721-4809-a0ae-173019591f85.png", 15500500 },
        });
        migrationBuilder.InsertData(table: "Adventures",
                                    columns: ["Id", "CampaignId", "Description", "IsPublic", "IsPublished", "Name", "OwnerId", "Type", "BackgroundId"],
                                    values: new object[,] {
            { new Guid("0196f86e-6669-78ee-95eb-4303c232295c"), null, "Test 1", false, false, "Test 1", new Guid("019639ea-c7de-7a01-8548-41edfccde206"), "Generic", new Guid("17b7f449-b2eb-41b5-9bca-a25b431e5281") },
            { new Guid("0196f86e-9220-769d-bf71-173f30d7177a"), null, "Test 2", false, false, "Test 2", new Guid("019639ea-c7de-7a01-8548-41edfccde206"), "Generic", new Guid("17b7f449-b2eb-41b5-9bca-a25b431e5281") },
            { new Guid("0196f86e-ce48-7b61-8dfa-3c1d535cc6c4"), null, "Test 3", false, false, "Test 3", new Guid("019639ea-c7de-7a01-8548-41edfccde206"), "Generic", new Guid("17b7f449-b2eb-41b5-9bca-a25b431e5281") },
            { new Guid("0196f86e-f929-7768-9b42-33e61727b389"), null, "Test 4", true, true, "Test 4", new Guid("00000000-0000-0000-0000-000000000000"), "Generic", new Guid("17b7f449-b2eb-41b5-9bca-a25b431e5281") },
            { new Guid("0196f86f-1c09-76a5-9f50-89ec627e5d00"), null, "Test 5", true, true, "Test 5", new Guid("00000000-0000-0000-0000-000000000000"), "Generic", new Guid("17b7f449-b2eb-41b5-9bca-a25b431e5281") },
            { new Guid("0196f86f-4212-78eb-8354-a990b4937911"), null, "Test 6", true, true, "Test 6", new Guid("00000000-0000-0000-0000-000000000000"), "Generic", new Guid("17b7f449-b2eb-41b5-9bca-a25b431e5281") }
        });
        migrationBuilder.InsertData(table: "Scenes",
                                    columns: ["Id", "AdventureId", "Description", "IsPublished", "Name", "OwnerId", "StageId", "Grid_Type", "Grid_CellSize_X", "Grid_CellSize_Y", "Grid_Offset_X", "Grid_Offset_Y", "Grid_Snap", "ZoomLevel"],
                                    values: new object[,] {
            { new Guid("0196f86e-6669-78ee-95eb-4303c232295f"), new Guid("0196f86e-6669-78ee-95eb-4303c232295c"), "Scene 1", false, "Scene 1", new Guid("019639ea-c7de-7a01-8548-41edfccde206"), new Guid("1309dbfb-0721-4809-a0ae-173019591f85"), "NoGrid", 50.0f, 50.0f, 0.0f, 0.0f, false, 1.0f },
        });
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder) {
        migrationBuilder.DeleteData(
            table: "Scenes",
            keyColumn: "Id",
            keyValue: new Guid("0196f86e-6669-78ee-95eb-4303c232295f"));

        migrationBuilder.DeleteData(
            table: "Adventures",
            keyColumn: "Id",
            keyValue: new Guid("0196f86e-6669-78ee-95eb-4303c232295c"));

        migrationBuilder.DeleteData(
            table: "Adventures",
            keyColumn: "Id",
            keyValue: new Guid("0196f86e-9220-769d-bf71-173f30d7177a"));

        migrationBuilder.DeleteData(
            table: "Adventures",
            keyColumn: "Id",
            keyValue: new Guid("0196f86e-ce48-7b61-8dfa-3c1d535cc6c4"));

        migrationBuilder.DeleteData(
            table: "Adventures",
            keyColumn: "Id",
            keyValue: new Guid("0196f86e-f929-7768-9b42-33e61727b389"));

        migrationBuilder.DeleteData(
            table: "Adventures",
            keyColumn: "Id",
            keyValue: new Guid("0196f86f-1c09-76a5-9f50-89ec627e5d00"));

        migrationBuilder.DeleteData(
            table: "Adventures",
            keyColumn: "Id",
            keyValue: new Guid("0196f86f-4212-78eb-8354-a990b4937911"));

        migrationBuilder.DeleteData(
            table: "Resources",
            keyColumn: "Id",
            keyValue: new Guid("1309dbfb-0721-4809-a0ae-173019591f85"));

        migrationBuilder.DeleteData(
            table: "Resources",
            keyColumn: "Id",
            keyValue: new Guid("17b7f449-b2eb-41b5-9bca-a25b431e5281"));
    }
}